[options]
console = no
execincludes = no
nofork = no
quiet = yes
timestamp = yes
execif = yes
hideconnect = yes

[files]
astctlgroup = asterisk
astctlowner = asterisk
astctlmode = 0660
astconfigsdir = /etc/asterisk
astmoddir = /usr/lib/asterisk/modules
astvarlibdir = /var/lib/asterisk
astdbdir = /var/lib/asterisk
astkeydir = /var/lib/asterisk
astlogdir = /var/log/asterisk
astsbindir = /usr/sbin

[directories]
astdir => /usr/lib/asterisk/modules
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astlogdir => /var/log/asterisk
astspooldir => /var/spool/asterisk
astrun dir => /var/run/asterisk

[compat]
pbx_lua = 1.0