; ============================================================================
; chan_websocket global settings
; ============================================================================

[global]
control_message_format = json
