; ============================================================================
; Asterisk Manager Interface (AMI) Configuration
; ============================================================================

[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0

[tito]
secret = tito
permit = 0.0.0.0/0.0.0.0
read = system,call,log,agent,user,dtmf
write = system,call,originate