[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[tito-ai]
type=endpoint
context=tito-outbound
transport=transport-tcp
disallow=all
allow=ulaw
allow=alaw
direct_media=no
aors=tito-ai

[tito-ai]
type=aor
max_contacts=1

[tito-inbound]
type=endpoint
context=tito-inbound-ari
transport=transport-udp
disallow=all
allow=ulaw
allow=alaw
direct_media=no
auth=tito-auth
aors=tito-aor

[tito-auth]
type=auth
auth_type=userpass
username=tito
password=tito123

[tito-aor]
type=aor
max_contacts=10

[tito-identify]
type=identify
endpoint=tito-inbound
match=0.0.0.0/0
